name: Project Workflow for Testing
on:
  push:
    branches:
      - main

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      
      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r main/project/requirements.txt

      # Add execution permissions to the tests script
      - name: Grant execute permission for the tests script
        run: chmod +x main/project/tests.sh

      # Run tests
      - name: Run tests
        run: |
          cd main
          ./project/tests.sh